sudo: required
dist: trusty
services:
  - docker

language: go

go:
  - 1.9
  - master

os:
  - linux

install: true

env:
  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"

# It's ok if our code fails on unstable development versions of Go.
matrix:
  allow_failures:
    - go: master
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

addons:
  apt:
    packages:
      - python-virtualenv
      - libpcap-dev

before_install:
  - go get github.com/elastic/beats

script:
  - make

after_success:
  # Copy full.cov to coverage.txt because codecov.io requires this file
